receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: detailed

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true

  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: "http://victoriametrics:8428/api/v1/write"

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
